[32mINFO    [0m test_ddt_for:test_ddt_for.py:48 Response Status Code: 200
[32mINFO    [0m test_ddt_for:test_ddt_for.py:49 Response Body: {"reason":"Bad credentials"}
[32mINFO    [0m test_ddt_for:test_ddt_for.py:65 Testing with username: Admin1