{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: '\\tests\\test\\\\datadriventesting\\testdata_ddt.xlsx'", "trace": "def test_create_auth_with_excel():\n        file_path = Path(__file__).parent / \"testdata_ddt.xlsx\"\n        file_path=\"\\tests\\test\\datadriventesting\\testdata_ddt.xlsx\"\n>       credentials=read_credentials_from_excel(file_path)\n\ntests\\test\\datadriventesting\\test_ddt_for.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests\\test\\datadriventesting\\test_ddt_for.py:15: in read_credentials_from_excel\n    workbook=openpyxl.load_workbook(filename=filepath)\n..\\.venv\\lib\\python3.10\\site-packages\\openpyxl\\reader\\excel.py:346: in load_workbook\n    reader = ExcelReader(filename, read_only, keep_vba,\n..\\.venv\\lib\\python3.10\\site-packages\\openpyxl\\reader\\excel.py:123: in __init__\n    self.archive = _validate_archive(fn)\n..\\.venv\\lib\\python3.10\\site-packages\\openpyxl\\reader\\excel.py:95: in _validate_archive\n    archive = ZipFile(filename, 'r')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <zipfile.ZipFile [closed]>, file = '\\tests\\test\\\\datadriventesting\\testdata_ddt.xlsx', mode = 'r', compression = 0, allowZip64 = True\ncompresslevel = None\n\n    def __init__(self, file, mode=\"r\", compression=ZIP_STORED, allowZip64=True,\n                 compresslevel=None, *, strict_timestamps=True):\n        \"\"\"Open the ZIP file with mode read 'r', write 'w', exclusive create 'x',\n        or append 'a'.\"\"\"\n        if mode not in ('r', 'w', 'x', 'a'):\n            raise ValueError(\"ZipFile requires mode 'r', 'w', 'x', or 'a'\")\n    \n        _check_compression(compression)\n    \n        self._allowZip64 = allowZip64\n        self._didModify = False\n        self.debug = 0  # Level of printing: 0 through 3\n        self.NameToInfo = {}    # Find file info given name\n        self.filelist = []      # List of ZipInfo instances for archive\n        self.compression = compression  # Method of compression\n        self.compresslevel = compresslevel\n        self.mode = mode\n        self.pwd = None\n        self._comment = b''\n        self._strict_timestamps = strict_timestamps\n    \n        # Check if we were passed a file-like object\n        if isinstance(file, os.PathLike):\n            file = os.fspath(file)\n        if isinstance(file, str):\n            # No, it's a filename\n            self._filePassed = 0\n            self.filename = file\n            modeDict = {'r' : 'rb', 'w': 'w+b', 'x': 'x+b', 'a' : 'r+b',\n                        'r+b': 'w+b', 'w+b': 'wb', 'x+b': 'xb'}\n            filemode = modeDict[mode]\n            while True:\n                try:\n>                   self.fp = io.open(file, filemode)\nE                   OSError: [Errno 22] Invalid argument: '\\tests\\test\\\\datadriventesting\\testdata_ddt.xlsx'\n\nC:\\msys64\\mingw64\\lib\\python3.10\\zipfile.py:1249: OSError"}, "start": 1735554586804, "stop": 1735554586805, "uuid": "1f4d0ec1-de13-45a4-85ee-dbac2627b677", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "31004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}