{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('username', <FixtureRequest for <Function test_create_auth_with_excel>>)", "trace": "file C:\\Users\\mutay\\OneDrive\\Documents\\courses\\PyATB\\code files\\pyProject1-AutomationFramework\\tests\\test\\datadriventesting\\test_ddt_for.py, line 47\n  def test_create_auth_with_excel(username,password):\nE       fixture 'username' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, extras, faker, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\mutay\\OneDrive\\Documents\\courses\\PyATB\\code files\\pyProject1-AutomationFramework\\tests\\test\\datadriventesting\\test_ddt_for.py:47"}, "start": 1735530970704, "stop": 1735530970704, "uuid": "b2d1fbec-8c76-415e-81c2-0a91cdcb02ac", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "11444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}