{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "NameError: name 'verify_http_status_code' is not defined", "trace": "def test_create_auth_with_excel():\n            file_path =\"C:/Users/mutay/OneDrive/Documents/courses/PyATB/code files/pyProject1-AutomationFramework/tests/test/datadriventesting/testdata_ddt.xlsx\"\n            credentials = read_credentials_from_excel(file_path=file_path)\n            print(credentials)\n            #Using for loop to send requests with all the data(each row) from the excel sheet\n            for user_cred in credentials:\n                username = user_cred[\"username\"]\n                password = user_cred[\"password\"]\n                print(username, password)\n                response = create_auth_request(username=username, password=password)\n                print(response.status_code)\n>               verify_http_status_code(response_data=response,expect_data=200)\nE               NameError: name 'verify_http_status_code' is not defined\n\ntests\\test\\datadriventesting\\test_ddt_for.py:47: NameError"}, "start": 1735567869015, "stop": 1735567870041, "uuid": "1f399722-1b4a-4d5b-8893-cfbe66d6edf7", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "25432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}